[package]
name = "ggst-bbs-unpacker"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
byteorder = "1"
clap = "3.0.0-beta.2"
eframe = { version = "0.13", optional = true }
rfd = { version = "0.4", optional = true }

[features]
default = ["gui"]
gui = ["eframe", "rfd"]
